# Site Settings
locale                   : "pt_BR" #
title                    : "renato ricco" #
description              : "Portfolio profissional." #
author                   : "Renato Ricco" #
tagline                  : "Designer Gráfico." #
logo                     : /assets/images/default/logo.png #
url                      : http://renatoricco.com # the base hostname & protocol for your site
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : rdricco/portifolio # GitHub username/repo-name
atom_feed:
  path                   : # blank (default) uses feed.xml

#Recent posts + miniabout
miniabout-text           : "Make a memorable experience. Let your brand act in a way that well exceeds users' expectations. See what we can do to help you."
miniabout-image          : "/assets/images/default/720-322.jpg"
miniabout-buttontext     : "O que eu faço"
miniabout-link           : "about.html"
#Contact page information
location         : "São Paulo - Brasil"
address          :
mapcoordinate    : "-23.5971369,-46.7623594"
#Footer information
email            : "contato@r-ricco.xyz"
copyright_url    : "http://r-ricco.xyz"
facebookurl      : "r.ricco"
github           : "rdricco"
instagram        : "r_ricco"
pinterest        :
tumblr           :
twitterurl       : "r_ricco"
youtube          :

#Google maps plugin
gmaps_APIKEY             : "AIzaSyDr89KPS6AUhP7e_ZBWBkDtOIDQaii8saU" #
gmaps_coordinates        : "-23.5971369,-46.7623594" #

#Communication plugins
formspree_email          : "contato@r-ricco.xyz" #Used on contact form
disqus_shortname         : "beta-project-from-r-ricco" #for comments on post pages

#### SHOP CONFIG
shopname                 : "Bernd Products" #
shoplogo                 : "/assets/images/default/720-400.png"
shopdescription          : "Bernd is a German luxury lifestyle brand founded in 1987 by Helmut Bernd. Today, it carries a range of products including clothings, furnitures, kitchenwares, and sports items." #
shopbuttontext           : "Visit website"
shopbuttonlink           : ""
paypal_id                : "renato.mur@gmail.com" #
paypal_currency          : "BRL" #

# Analytics & SEO
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-88472320-1"
google_site_verification : "ANdJ9Vv8T9IUc75gMVb4ms3hd2Dgj1qMRKZzgEg2mRI"

# Social Sharing
twitter:
  username               : "r_ricco"
facebook:
  app_id                 : "771692052969152" # used on facebook analytics
  publisher              : # use only for facebook pages
  username               : "r.ricco" # your personal profile
og_image                 : "/assets/images/default/470-247.jpg" # Open Graph/Twitter default site image
# - For specifying social profiles:
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links                  : # An array of links to social media profiles
    - https://twitter.com/r_ricco
    - https://www.facebook.com/r.ricco
    - https://github.com/rdricco

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single_post
      comments: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      comments: false
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: work_fullwidth
      comments: false
  # _products
  - scope:
      path: ""
      type: products
    values:
      layout: shop-item
      comments: false

#Collections
collections:
  portfolio:
    output: true
    title: Portfolio
    permalink: /portfolio/:path/
  products:
    output: false
    permalink: /products/:path/

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap

# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /blog/page:num/ # change to /page:num/ if you want to use paginate posts on home
timezone: America/Sao_Paulo # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#SASS compression
sass:
    sass_dir: _sass
    style: :compressed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
